package ast;

public enum tipoExpresion {
	 NOMBRE, CREACIONVECTOR, CREACIONVECTOR2,
	 LLAMADAFUNCRETURN, ACCESOPUNTERO, ACCESOSTRUCT,
	 ACCESOSTRUCTPUNTERO, ACCESOVECTOR, AND, CARACT,
	 CORCHETESVECTOR, DECIMAL, DISTINTO, DIV, 
	 ENTERO, ENTRECORCHETES, ENTREPARENTESIS, 
	 IGUALIGUAL, MAYOR, MAYORIGUAL, MENOR, MENORIGUAL,
	 MOD, MUL,  NOT, OPRESTA, OPSUMA, OR, RESTA, SUMA, FALSE, TRUE,
	 INT, BOOL, DOUBLE, VECTOR, EXPRNEW
	 
}
