package ast;

public enum tipoSubprograma {
	FOR1, FOR2, WHILE, DECVAR, ASIGNACION, DECTIPO,
	DECFUNCIONCONRETURN, DECFUNCIONSINRETURN,DECSTRUCT,
	DECENUM, LLAMADAFUNCIONVOID, IFSINELSE, IFCONELSE, SWITCH

}
