
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 23 15:29:01 CEST 2021
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 30;
  public static final int DISTINTO = 58;
  public static final int NOMBREV = 11;
  public static final int NOMBRET = 10;
  public static final int CHAR = 16;
  public static final int PUNTOYCOMA = 5;
  public static final int ABRECORCHETE = 50;
  public static final int CASE = 29;
  public static final int RESTA = 43;
  public static final int DOUBLE = 18;
  public static final int INT = 17;
  public static final int FOR = 2;
  public static final int NOT = 49;
  public static final int MENORIGUAL = 41;
  public static final int AND = 38;
  public static final int ELSEIF = 34;
  public static final int IGUAL = 14;
  public static final int CARACTER = 55;
  public static final int CIERREPARENTESIS = 4;
  public static final int OR = 37;
  public static final int IN = 12;
  public static final int BOOL = 15;
  public static final int DIV = 44;
  public static final int SUMA = 42;
  public static final int TYPEDEF = 27;
  public static final int IF = 33;
  public static final int MAYORIGUAL = 40;
  public static final int DECIMAL = 54;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int TRUE = 47;
  public static final int APERTPARENTESIS = 3;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int MUL = 46;
  public static final int COMA = 7;
  public static final int MODULO = 45;
  public static final int NULL = 52;
  public static final int CIERRELLAVES = 9;
  public static final int MENOR = 21;
  public static final int CIERRACORCHETE = 51;
  public static final int BREAK = 31;
  public static final int VOID = 57;
  public static final int VECTOR = 20;
  public static final int SWITCH = 28;
  public static final int MAYOR = 22;
  public static final int ENT = 53;
  public static final int FLECHA = 56;
  public static final int ELSE = 35;
  public static final int PORREFERENCIA = 24;
  public static final int PUNTO = 6;
  public static final int ENUM = 25;
  public static final int IGUALIGUAL = 39;
  public static final int WHILE = 13;
  public static final int APERTLLAVES = 8;
  public static final int DEFAULT = 32;
  public static final int STRING = 19;
  public static final int FALSE = 48;
  public static final int STRUCT = 26;
}

